import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import { ThemeProvider } from "@/context/theme-provider"
import ".././globals.css";
import ContextProvider from "@/context/ContextProvider";
import dynamic from "next/dynamic";
const NavBar=dynamic(()=>import('@/components/shared/NavBar'),{ssr:false});

const poppins = Poppins({ subsets: ["latin"], weight: ['400', '500', '600', '700']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={`${poppins.className} min-h-[100vh] w-[100vw]  flex flex-col`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <ContextProvider>
            <NavBar/>
              {children}
            </ContextProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
